/**
 * @file cpu_core.h
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * CPU_CORE - Configures a CPU core to perform specified configuration made on the GUI.
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved. 
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 */
/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#ifndef CPU_CORE_H
#define CPU_CORE_H

#include "DAVE_Common.h"
#include "IfxCpu.h"
#include "IfxCpu_Intrinsics.h"
#include "IfxCpu_Trap.h"

/***********************************************************************************************************************
 * enumS
 **********************************************************************************************************************/
/**
 * @ingroup CPU_CORE_enumerations
 * @{
 */
/**
 * @brief enum to describe the possible status values, returned by CPU_CORE APIs.
 */
typedef enum CPU_CORE_STATUS
{
  CPU_CORE_STATUS_SUCCESS = 0U,                             /**< Indicates App initialization state successful */
  CPU_CORE_STATUS_FAILURE                                   /**< Unknown error */

} CPU_CORE_STATUS_t;

/**
 * @brief enum to provide the possible I/O mode values.
 */
typedef enum CPU_CORE_IOMODE
{
  CPU_CORE_IOMODE_USER0 = 0U,                               /**< User-0 Mode */
  CPU_CORE_IOMODE_USER1,                                    /**< User-1 Mode */
  CPU_CORE_IOMODE_SUPERVISOR,                               /**< Supervisor Mode */

} CPU_CORE_IOMODE_t;
/**
 * @}
 */

/**
 * @ingroup CPU_CORE_datastructures
 * @{
 */
/**
 * @brief Structure for holding I/O mode configuration
 */
typedef struct CPU_CORE_IOMODE_CONF
{
  boolean u1_ios;                                           /**< User-1 Peripheral access as supervisor */
  boolean u1_ied;                                           /**< User-1 Instruction execution disable */
}CPU_CORE_IOMODE_CONF_t;

/**
 * @brief Structure for holding the MPU range information
 */
typedef struct CPU_CORE_MPU_RANGE
{
  uint32 start;                                             /**< Start address */
  uint32 end;                                               /**< End address */
} CPU_CORE_MPU_RANGE_t;

/**
 * @brief Structure for holding the MPU set information
 */
typedef struct CPU_CORE_MPU_SET
{
  uint32 read;                                              /**< readable ranges (every bit represetns active range) */
  uint32 write;                                             /**< writable ranges (every bit represetns active range) */
  uint32 execute;                                           /**< executable ranges (every bit represetns active range) */
} CPU_CORE_MPU_SET_t;

/**
 * @brief Structure for holding the configuration parameters for MPU initialization
 */
typedef struct CPU_CORE_MPU_CONF
{
  struct
  {
    uint32 num;                                             /**< number of defined data ranges */
    CPU_CORE_MPU_RANGE_t * ranges;                          /**< adress info of each data range */
  } data_range;
  struct
  {
    uint32 num;                                             /**< number of defined code ranges */
    CPU_CORE_MPU_RANGE_t * ranges;                          /**< adress info of each code range */
  } code_range;
  struct
  {
    uint32 num;                                             /**< number of defined sets */
    CPU_CORE_MPU_SET_t   * sets;                            /**< range info of each set */
  } set;
} CPU_CORE_MPU_CONF_t;

/**
 * @brief Structure for holding the configuration parameters of the CPU core.
 */
typedef struct CPU_CORE_CONF
{
  CPU_CORE_IOMODE_CONF_t   iomode_config;                   /**< I/O mode configuration */
  CPU_CORE_MPU_CONF_t    * mpu_config;                      /**< MPU configuration */
} CPU_CORE_CONF_t;

/**
 * @brief Handler structure with pointers to static parameters.
 */
typedef struct CPU_CORE
{
  const CPU_CORE_CONF_t * const app_config;                 /**< CPU_CORE configuration structure pointer */
  Ifx_CPU                     * cpu;                        /**< CPU object to handle */
  boolean                       app_is_initialized;         /**< APP initialization status */
} CPU_CORE_t;
/**
 * @}
 */

#include "cpu_core_private.h"

/***********************************************************************************************************************
 * API Prototypes
 **********************************************************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @ingroup CPU_CORE_apidoc
 * @{
 */

/**
 * @brief Get the CPU_CORE APP version.
 * @return ACS_APP_VERSION_t APP version information (major, minor and patch number)
 *
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 * #include "DAVE.h"
 * 
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 * 
 * void core0_main(void)
 * {
 *   ACS_APP_VERSION_t app_version;
 * 
 *   IfxCpu_enableInterrupts();
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 * 
 *   DAVE_STATUS_t status = DAVE_Init();           // Initialization of DAVE APPs
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     while (1) {
 *       // Implement your code to handle the error here!
 *     }
 *   }
 * 
 *   app_version = CPU_CORE_GetAppVersion();
 *   if ((app_version.major == 1) && (app_version.minor == 0) && (app_version.patch == 2)) {
 *     // version of APP met
 *   }
 * 
 *   while (1);
 * }
 * @endcode
 */
ACS_APP_VERSION_t CPU_CORE_GetAppVersion(void);

/**
 * @brief Function to initialize a CPU core to perform specified configuration made on the GUI
 * in GUI.
 * @param handle Pointer to static content of APP configuration.
 * @return CPU_CORE_STATUS_t: Status of initialization.\n
 *   @ref CPU_CORE_STATUS_SUCCESS - on successful initialization.\n
 *   @ref CPU_CORE_STATUS_FAILURE - if initialization fails.\n
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 * #include "DAVE.h"
 * 
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 * 
 * void core0_main(void)
 * {
 *   IfxCpu_enableInterrupts();
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 * 
 *   CPU_CORE_STATUS_t status = CPU_CORE_Init(&CPU_CORE_0);     // Initialization of APP
 *   if (status != CPU_CORE_STATUS_SUCCESS) {
 *     while (1) {
 *       // Implement your code to handle the error here!
 *     }
 *   }
 * 
 *   while (1);
 * }
 * @endcode
 * @note If the core number assigned to the APP instance is 0, this function is automatically called from DAVE_Init() in the Cpu0_Main() function.
 *       Otherwise (when the core number is not 0), this function must be called from the respective main function,
 *       since CPU core configuration must be performed from the core to be configured.
 */
CPU_CORE_STATUS_t CPU_CORE_Init(CPU_CORE_t *handle);

/**
 * @brief Function to set the I/O mode
 * @param handle Pointer to static content of APP configuration.
 * @param iomode I/O mode
 * @return CPU_CORE_STATUS_t: Status of initialization.\n
 * @ref CPU_CORE_STATUS_SUCCESS - on successful initialization.\n
 * @ref CPU_CORE_STATUS_FAILURE - if initialization fails.\n
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 * #include "DAVE.h"
 * 
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 * 
 * void core0_main(void)
 * {
 *   // After core reset, the I/O mode is set to Supervisor by default
 * 
 *   IfxCpu_enableInterrupts();
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 * 
 *   DAVE_STATUS_t status = DAVE_Init();           // Initialization of DAVE APPs
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     while (1) {
 *       // Implement your code to handle the error here!
 *     }
 *   }
 *   
 *   CPU_CORE_SetIOMode(&CPU_CORE_0, CPU_CORE_IOMODE_USER0);  // change I/O mode to User-0
 *   
 *   // Hereafter, the I/O mode cannot be back to Supervisor.
 *   // It's possible only using stack pop that contains PSW as supervisor
 *   
 *   while (1);
 * }
 * @endcode
 * @note This function needs to be declared as inline because the Program Status Word (PSW) is one of the registers
 *       automatically saved to the Context Save Area (CSA) when a function is called.
 *       If this function was not declared as inline, the Upper Context (16 registers including the PSW) would be
 *       automatically saved to the CSA and re-loaded when the function return, thus losing the change in the PSW.
 *       In addition, note that this function must be called with the I/O mode as Supervisor.
 *       So once the I/O mode is changed to not Supervisor, it cannot be back to Supervisor using this function.
 */
IFX_INLINE CPU_CORE_STATUS_t CPU_CORE_SetIOMode(CPU_CORE_t *handle, CPU_CORE_IOMODE_t iomode)
{
  CPU_CORE_STATUS_t status = CPU_CORE_STATUS_FAILURE;

  /* This function handles only the I/O mode of its own core.
   * When other cores than itself is specified in the handle, the call will be ignored and returns failure with doing nothing.
   */
  IfxCpu_Id cpu_id = IfxCpu_getCoreId();
  if (((cpu_id == IfxCpu_Id_0) && (handle->cpu == &MODULE_CPU0))
#ifdef MODULE_CPU1
       ||
      ((cpu_id == IfxCpu_Id_1) && (handle->cpu == &MODULE_CPU1))
#endif
#ifdef MODULE_CPU2
       ||
      ((cpu_id == IfxCpu_Id_2) && (handle->cpu == &MODULE_CPU2))
#endif
#ifdef MODULE_CPU3
       ||
      ((cpu_id == IfxCpu_Id_3) && (handle->cpu == &MODULE_CPU3))
#endif
#ifdef MODULE_CPU4
       ||
      ((cpu_id == IfxCpu_Id_4) && (handle->cpu == &MODULE_CPU4))
#endif
#ifdef MODULE_CPU5
       ||
      ((cpu_id == IfxCpu_Id_6) && (handle->cpu == &MODULE_CPU5))
#endif
     )
  {
    Ifx_CPU_PSW PSW_register_val;
    PSW_register_val.U = __mfcr(CPU_PSW);               /* Get the Program Status Word (PSW) register value         */
    PSW_register_val.B.IO = iomode;                     /* Set the PRS bitfield to change the I/O mode              */
    __mtcr(CPU_PSW, PSW_register_val.U);                /* Set the Program Status Word (PSW) register               */
  }
  return status;
}

/**
 * @brief Function to set the given Protection Set as active
 * @param handle Pointer to static content of APP configuration.
 * @param protection_set Protection set number.
 * @return CPU_CORE_STATUS_t: Status of initialization.\n
 * @ref CPU_CORE_STATUS_SUCCESS - on successful initialization.\n
 * @ref CPU_CORE_STATUS_FAILURE - if initialization fails.\n
 * \par<b>Example Usage</b><br>
 * @code
 * #include "Ifx_Types.h"
 * #include "IfxCpu.h"
 * #include "IfxScuWdt.h"
 * #include "DAVE.h"
 * 
 * IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
 * 
 * void core0_main(void)
 * {
 *   // After core reset, the I/O mode is set to Supervisor by default, and MPU is not enabled
 * 
 *   IfxCpu_enableInterrupts();
 *   IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
 *   IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
 *   IfxCpu_emitEvent(&g_cpuSyncEvent);
 *   IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
 * 
 *   DAVE_STATUS_t status = DAVE_Init();           // Initialization of DAVE APPs
 * 
 *   // After CPU_CORE_Init() is called from DAVE_Init(), MPU will be enabled if GUI parameter is specified so
 *   // And the protection set will be 0 by default
 * 
 *   if (status != DAVE_STATUS_SUCCESS) {
 *     while (1) {
 *       // Implement your code to handle the error here!
 *     }
 *   }
 *   
 *   // change protection set to 1. This operation shall be done by Supervisor
 *   if (CPU_CORE_SetActiveProtectionSet(&CPU_CORE_0, 1) == CPU_CORE_STATUS_SUCCESS) {
 *     // Hereafter, the protection set 1 is activated
 *   }
 *   else {
 *     // The protection set number have to be smaller than number of defined protected range.
 *     // When you call this function when the I/O mode is other than Supervisor, a trap TCN1/TIN1 PRIV will be raised
 *   }
 *   while (1);
 * }
 * @endcode
 * @note This function needs to be declared as inline because the Program Status Word (PSW) is one of the registers
 *       automatically saved to the Context Save Area (CSA) when a function is called.
 *       If this function was not declared as inline, the Upper Context (16 registers including the PSW) would be
 *       automatically saved to the CSA and re-loaded when the function return, thus losing the change in the PSW.
 *       In addition, note that this function must be called with the I/O mode as Supervisor.
 */
IFX_INLINE CPU_CORE_STATUS_t CPU_CORE_SetActiveProtectionSet(CPU_CORE_t *handle, uint8 protection_set)
{
  CPU_CORE_STATUS_t status = CPU_CORE_STATUS_FAILURE;

  /* This function handles only the MPUs of its own core.
   * When other cores than itself is specified in the handle, the call will be ignored and returns failure with doing nothing.
   */
  IfxCpu_Id cpu_id = IfxCpu_getCoreId();
  if (((cpu_id == IfxCpu_Id_0) && (handle->cpu == &MODULE_CPU0))
#ifdef MODULE_CPU1
       ||
      ((cpu_id == IfxCpu_Id_1) && (handle->cpu == &MODULE_CPU1))
#endif
#ifdef MODULE_CPU2
       ||
      ((cpu_id == IfxCpu_Id_2) && (handle->cpu == &MODULE_CPU2))
#endif
#ifdef MODULE_CPU3
       ||
      ((cpu_id == IfxCpu_Id_3) && (handle->cpu == &MODULE_CPU3))
#endif
#ifdef MODULE_CPU4
       ||
      ((cpu_id == IfxCpu_Id_4) && (handle->cpu == &MODULE_CPU4))
#endif
#ifdef MODULE_CPU5
       ||
      ((cpu_id == IfxCpu_Id_6) && (handle->cpu == &MODULE_CPU5))
#endif
     )
  {
    if (protection_set < handle->app_config->mpu_config->set.num)
    {
      set_active_protection_set(protection_set);
      status = CPU_CORE_STATUS_SUCCESS;
    }
  }
  return status;
}

/**
 * @}
 */

#include "cpu_core_conf.h"

#ifdef __cplusplus
}
#endif

#endif /* CPU_CORE_H_ */

/* CODE_BLOCK_END */
