/**
 * @file freertos_aurix.c
 *
 * NOTE:
 * This file is generated by ACS. Any manual modification done to this file will be lost when the code is regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * freertos_aurix - FreeRTOS implementation for AURIX devices
 *
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved. 
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 ***********************************************************************************************************************
 *
 * @endcond
 *
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "freertos_aurix.h"

/**********************************************************************************************************************
 * API IMPLEMENTATION
 **********************************************************************************************************************/
/*
 * Get the version of the TIMER APP.
 */
ACS_APP_VERSION_t FREERTOS_AURIX_GetAppVersion(void)
{
  ACS_APP_VERSION_t version;
  version.major = FREERTOS_AURIX_MAJOR_VERSION;
  version.minor = FREERTOS_AURIX_MINOR_VERSION;
  version.patch = FREERTOS_AURIX_PATCH_VERSION;
  return version;
}

/*
 * This function initializes a TIMER APP based on user configuration.
 */
FREERTOS_AURIX_STATUS_t FREERTOS_AURIX_Init(FREERTOS_AURIX_t *handle)
{
  FREERTOS_AURIX_STATUS_t status = FREERTOS_AURIX_STATUS_SUCCESS;
  IFX_ASSERT(IFX_VERBOSE_LEVEL_FAILURE, (handle != NULL));

  if (!handle->app_is_initialized)
  {
#ifdef TIMER_STM_H
    if ((handle->app_config->timer_source == FREERTOS_AURIX_TIMER_SOURCE_APP_STM_CMP0) ||
        (handle->app_config->timer_source == FREERTOS_AURIX_TIMER_SOURCE_APP_STM_CMP1))
    {
      if (TIMER_STM_Init((TIMER_STM_t *)handle->timer_app_handle) != TIMER_STM_STATUS_SUCCESS)
      {
        status = FREERTOS_AURIX_STATUS_FAILURE;
      }
    }
#endif
#ifdef TIMER_GTM_H
    if (handle->app_config->timer_source == FREERTOS_AURIX_TIMER_SOURCE_APP_GTM)
    {
      if (TIMER_GTM_Init((TIMER_GTM_t *)handle->timer_app_handle) != TIMER_GTM_STATUS_SUCCESS)
      {
        status = FREERTOS_AURIX_STATUS_FAILURE;
      }
    }
#endif
    handle->app_is_initialized = TRUE;
  }

  return (status);
}

void FREERTOS_AURIX_SyscallHandler(IfxCpu_Trap trap_info)
{
  switch (trap_info.tId)
  {
  case 0:
    vPortSyscallYield();
    break;

  default:
    break;
  }
}

/* CODE_BLOCK_END */
